apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  labels:
    name: db-deploy
  namespace: bggns
spec:
  replicas: 3
  selector:
    matchLabels:
      name: db-pod
  template:
    metadata:
      name: db-pod
      labels:
        name: db-pod
    spec:
      containers:
      - name: db-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  labels:
    name: bggdb-svc
  namespace: bggns
spec:
  type: ClusterIP
  selector:
    name: db-pod
  ports:
  - port: 3306
    targetPort: 3306
